import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineMail,
  AiOutlineMobile,
} from "react-icons/ai";
import Image from "next/image";
import franz from "../public/franzbig.png";
import photogram from "../public/photogram.png";
import cryptocurrent from "../public/cryptocurrent.png";
import resume from "../public/FranzCadienteResume.pdf";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Franz Cadiente</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main className=" bg-yellow-50 px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            {/*<h1 className=" text-xl font-burtons">Franz Cadiente</h1>
            <ul className="flex items-center">
              <li>
                <a
                  className=" bg-orange-500 text-white px-4 py-2  ml-8"
                  href={resume} target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul> */}
          </nav>
          <div className="text-center p-2">
            <h2 className="text-5xl py-2 text-orange-500 font-medium md:text-6xl">
              Franz Cadiente
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Front-End Developer.</h3>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-orange-300 rounded-full w-80 h-80 mt-10 md:h-96 md:w-96">
            <Image src={franz} layout="fill" objectFit="cover" />
          </div>
          <div className="text-center p-2">
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
              I have a strong foundation in HTML, CSS, JavaScript, React,
              Tailwind, and SCSS as a front-end developer. I am excellent at
              creating and managing user-friendly responsive websites. My
              speciality is creating clean, optimised code, using
              state-of-the-art development tools and methods, to create dynamic,
              engaging interfaces. I also enjoy working with cross-functional
              teams to create excellent web applications because I am a strong
              team player.
            </p>
          </div>
          <div className=" text-5xl flex justify-center gap-10 py-5 text-orange-500">
            <a
              href="https://www.linkedin.com/in/franzcadiente/"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="mailto:fmpcadiente@gmail.com">
              <AiOutlineMail />
            </a>
            <a href="https://github.com/franzcad1" target="_blank">
              <AiFillGithub />
            </a>
          </div>
          <div>
            <h3 className="text-3xl py-1">Tech Stack</h3>
            <div className=" text-5xl flex justify-center gap-5 py-5 text-orange-500">
              <img src="https://skillicons.dev/icons?i=html"></img>
              <img src="https://skillicons.dev/icons?i=css"></img>
              <img src="https://skillicons.dev/icons?i=js"></img>
              <img src="https://skillicons.dev/icons?i=ts"></img>
              <img src="https://skillicons.dev/icons?i=react"></img>
              <img src="https://skillicons.dev/icons?i=redux"></img>
              <img src="https://skillicons.dev/icons?i=cs"></img>
              <img src="https://skillicons.dev/icons?i=dotnet"></img>
              <img src="https://skillicons.dev/icons?i=nodejs"></img>
              <img src="https://skillicons.dev/icons?i=py"></img>
              <img src="https://skillicons.dev/icons?i=java"></img>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Here are some of the projects that I have worked on that show my
              skill-set.
            </p>
          </div>
          <div className="bg-orange-200 rounded-lg h-72 justify-center items-center flex flex-row mt-5">
            <div className="w-3/6 p-2">
              <a href="https://photo-gram-beta.vercel.app/" target="_blank">
                <Image src={photogram} className="rounded-lg object-cover" />
              </a>
            </div>
            <div className="w-3/6 text-center p-2">
              <h2 className="text-2xl py-5">PhotoGram</h2>
              <p>
                {" "}
                A high-quality image search and storage application making use
                of the Unsplash REST API.{" "}
              </p>
              <div className="flex flex-row justify-center gap-5">
                <div className=" bg-orange-500 text-white px-4 py-2 mt-5">
                  React
                </div>
                <div className=" bg-orange-500 text-white px-4 py-2 mt-5">
                  Redux
                </div>
                <div className=" bg-orange-500 text-white px-4 py-2 mt-5">
                  Styled-Components
                </div>
              </div>
              <div className="flex flex-row justify-center gap-5 my-5">
                <div className="flex flex-row justify-center">
                  <a
                    href="https://github.com/franzcad1/PhotoGram"
                    target="_blank"
                    className="items-center justify-center flex gap-1"
                  >
                    <p>Code</p>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                    >
                      <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                    </svg>{" "}
                  </a>
                </div>
                <div className="flex flex-row justify-center gap-1">
                  <a
                    href="https://photo-gram-beta.vercel.app/"
                    target="_blank"
                    className="items-center justify-center flex gap-1"
                  >
                    <p>Live Demo</p>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      x="0px"
                      y="0px"
                      width="24"
                      height="24"
                      viewBox="0 0 30 30"
                    >
                      <path d="M 25.980469 2.9902344 A 1.0001 1.0001 0 0 0 25.869141 3 L 20 3 A 1.0001 1.0001 0 1 0 20 5 L 23.585938 5 L 13.292969 15.292969 A 1.0001 1.0001 0 1 0 14.707031 16.707031 L 25 6.4140625 L 25 10 A 1.0001 1.0001 0 1 0 27 10 L 27 4.1269531 A 1.0001 1.0001 0 0 0 25.980469 2.9902344 z M 6 7 C 4.9069372 7 4 7.9069372 4 9 L 4 24 C 4 25.093063 4.9069372 26 6 26 L 21 26 C 22.093063 26 23 25.093063 23 24 L 23 14 L 23 11.421875 L 21 13.421875 L 21 16 L 21 24 L 6 24 L 6 9 L 14 9 L 16 9 L 16.578125 9 L 18.578125 7 L 16 7 L 14 7 L 6 7 z"></path>
                    </svg>
                  </a>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-orange-200 rounded-lg h-72 justify-center items-center flex flex-row mt-5">
            <div className="w-3/6 text-center p-2">
              <h2 className="text-2xl py-5">CryptoCurrent</h2>
              <p>
                A cryptocurrency index application built with React and Redux
                that uses the CoinGecko REST API allowing users to browse,
                compare and save their favorite coins for tracking purposes.
              </p>
              <div className="flex flex-row justify-center gap-5">
                <div className=" bg-orange-500 text-white px-4 py-2 mt-5">
                  React
                </div>
                <div className=" bg-orange-500 text-white px-4 py-2 mt-5">
                  Redux
                </div>
                <div className=" bg-orange-500 text-white px-4 py-2 mt-5">
                  Charts.js
                </div>
              </div>
              <div className="flex flex-row justify-center gap-5 my-5">
                <div className="flex flex-row justify-center">
                  <a
                    href="https://github.com/franzcad1/cryptocurrent"
                    target="_blank"
                    className="items-center justify-center flex gap-1"
                  >
                    <p>Code</p>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                    >
                      <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                    </svg>{" "}
                  </a>
                </div>
                <div className="flex flex-row justify-center gap-1">
                  <a
                    href="https://cryptocurrent.vercel.app/"
                    target="_blank"
                    className="items-center justify-center flex gap-1"
                  >
                    <p>Live Demo</p>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      x="0px"
                      y="0px"
                      width="24"
                      height="24"
                      viewBox="0 0 30 30"
                    >
                      <path d="M 25.980469 2.9902344 A 1.0001 1.0001 0 0 0 25.869141 3 L 20 3 A 1.0001 1.0001 0 1 0 20 5 L 23.585938 5 L 13.292969 15.292969 A 1.0001 1.0001 0 1 0 14.707031 16.707031 L 25 6.4140625 L 25 10 A 1.0001 1.0001 0 1 0 27 10 L 27 4.1269531 A 1.0001 1.0001 0 0 0 25.980469 2.9902344 z M 6 7 C 4.9069372 7 4 7.9069372 4 9 L 4 24 C 4 25.093063 4.9069372 26 6 26 L 21 26 C 22.093063 26 23 25.093063 23 24 L 23 14 L 23 11.421875 L 21 13.421875 L 21 16 L 21 24 L 6 24 L 6 9 L 14 9 L 16 9 L 16.578125 9 L 18.578125 7 L 16 7 L 14 7 L 6 7 z"></path>
                    </svg>
                  </a>
                </div>
              </div>
            </div>
            <div className="w-3/6 p-2">
              <a href="https://cryptocurrent.vercel.app/" target="_blank">
                <Image
                  src={cryptocurrent}
                  className="rounded-md object-cover"
                />
              </a>
            </div>
          </div>
        </section>
        <p className="text-sm text-center p-6 text-gray-800 pt-10">
          Designed by Franz Cadiente {new Date().getFullYear()} ©.
        </p>
      </main>
    </div>
  );
}
